init
run:

    yarn

see:

    yarn run build

failing:
Hash: 88372ac31a7eb43137a4
Version: webpack 3.9.1
Time: 4586ms
                       Asset    Size  Chunks                    Chunk Names
main-88372ac31a7eb43137a4.js  328 kB       0  [emitted]  [big]  main
   [0] ./assets/ts/app.ts 738 bytes {0} [built] [1 error]
   [5] (webpack)/buildin/global.js 509 bytes {0} [built]
    + 7 hidden modules

ERROR in ./assets/ts/app.ts
[tsl] ERROR in /tmp/tscript/assets/ts/app.ts(10,16)
      TS2339: Property 'hash' does not exist on type 'typeof "/tmp/tscript/node_modules/tweetnacl/nacl-fast"'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜ tscript git:(master) ✗>

Compiling manually seems to work fine:

➜ tscript git:(master) ✗>./node_modules/typescript/bin/tsc assets/ts/app.ts
➜ tscript git:(master) ✗>